# name: mobile-release

# on: [push]

# jobs:
#   release-ios:
#     runs-on: ubuntu-latest
#     steps:
#       - name: ğŸ— Setup repo
#         uses: actions/checkout@v3

#       - name: ğŸ— Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20.5.0
#           cache: yarn

#       - name: ğŸ— Setup EAS
#         uses: expo/expo-github-action@v8
#         with:
#           eas-version: latest
#           token: ${{ secrets.EXPO_TOKEN }}

#       - name: ğŸ“¦ Install dependencies
#         run: yarn install

#       - name: ğŸš€ Build app
#         run: |
#           cd apps/mobile;
#           eas build -p ios -e production --non-interactive --auto-submit
